shopgate/connect-integration-magento

release/build_release_package.sh, release/magento_package.php
Tested with tag build
3.1.0 -> https://travis-ci.org/augsteyer/cloud-integration-magento/builds/306226514
=> WEBC-442 Adjusting tag syntax from v3.0.0 to 3.0.0

src/app/code/community/Shopgate/Cloudapi/Block/Checkout/Onepage/Success.php, src/app/design/frontend/base/default/template/shopgate/cloudapi/header/checkout/onepage/success.phtml
Please test with iOS, i've tested it with Android, looks good so far.
=> WEBC-573 - Fixed issue with closing InAppBrowser

src/app/code/community/Shopgate/Cloudapi/Helper/Api2/Quote.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Carts/Rest.php
=> WEBC-597 Adjustment of logic and styling

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Categories/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Categories/Rest/Admin/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Categories/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/controllers/V2Controller.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, tests/postman/newman/collection.json, tests/postman/newman/globals.json
Blank endpoints ready to be extended. I don't believe we need anything else.
=> CCP-145 Mage: category endpoint stubs

CHANGELOG.md, README.md, composer.json
Changing composer type to allow for download using Magento composer installer
=> Composer type change

src/app/code/community/Shopgate/Cloudapi/sql/shopgate_cloudapi_setup/mysql4-upgrade-3.0.0-3.1.0.php
Fixing installation script for 3.0.0 -> 3.1.0 and backwards compatible table migration
=> Table migration fix

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Carts/Items/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Carts/Items/Type/Product.php
=> PI-8745: also collect shipping methods when updating/deleting cart items

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Helper/Frontend/Quote/Token.php
=> PI-8746: not deleting checkout token anymore

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, tests/postman/newman/collection.json
Can now call customers/:id/addresses to retrieve addresses of a specific customer.
=> Magento 2064 endpoint customer addre

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, src/app/locale/de_DE/Shopgate_Cloudapi.csv, tests/postman/newman/collection.json
=> MAGENTO-2060: Added api endpoint for deleting customer addresses

.travis.yml, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Validator.php, tests/postman/magento_setup.sh, tests/postman/n98-scripts/n98-setup.magerun, tests/postman/newman/collection.json, tests/postman/newman/globals.json
Adding the ability to set default billing and shipping. Also added some tests to check for guests trying to manipulate customer data and a second customer trying to access another customer's data.
=> Magento 2102 endpoint address add default

src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest.php, tests/postman/newman/collection.json
=> MAGENTO-2099: changed error code for deleting default address

src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest/Customer/V2.php, src/shell/shopgate_cloudapi.php, tests/postman/newman/collection.json
Added `region_code` to the getAddress endpoint output
=> MAGENTO-2149 Added region_code & tests

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Acl/Customers/Filter.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Addresses/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Password/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Password/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Password/Validator.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Validator.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, tests/postman/newman/collection.json, tests/postman/newman/globals.json
Implemented endpoint to change passwords with strict block for any incoming data that is not password or oldPassword. Cleaned up some tests for updateUser story.
=> Magento 2129 endpoint password

release/build_release_package.sh, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Email/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Email/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Email/Validator.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, tests/postman/newman/collection.json
=> Magento 2130 api endpoint to update e mail address

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Email/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Customers/Email/Validator.php, src/app/code/community/Shopgate/Cloudapi/Model/Auth.php, src/app/code/community/Shopgate/Cloudapi/Model/Frontend/Observer/CustomerRegisterSuccess.php, src/app/code/community/Shopgate/Cloudapi/Model/OAuth2/Db/Pdo.php, tests/postman/newman/collection.json
=> Magento 2130 keep tokens valid after email update

src/app/code/community/Shopgate/Cloudapi/etc/config.xml
Adding some styles to hide the sidebar on history page and overview page
=> MAGENTO-2312 Adding styles that remove the order history sidebar

docs/swagger.yaml, tests/postman/newman/collection.json
Added test for empty password, adjusted swagger to not require password
=> Magento 2314 add empty psw tests

CHANGELOG.md, docs/swagger.yaml, src/app/code/community/Shopgate/Cloudapi/Model/Auth.php, src/app/code/community/Shopgate/Cloudapi/Model/OAuth2/Server.php, src/lib/Shopgate/cloud-integration-magento-oauth2/composer.json, src/lib/Shopgate/cloud-integration-magento-oauth2/composer.lock, src/lib/Shopgate/cloud-integration-magento-oauth2/src/GrantType/FacebookCredentials.php, src/lib/Shopgate/cloud-integration-magento-oauth2/src/Storage/FacebookCredentialsInterface.php, src/lib/Shopgate/cloud-integration-magento-oauth2/src/Storage/Pdo.php, tests/postman/newman/collection.json
Added facebook login strategy, see swagger documentation attached for details
=> Magento 2315 facebook oauth

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Helper/Api2/Quote.php
We did not consider the settings for printing shipping costs with or without taxes.
=> MAGENTO-2330: fixed shipping amount in getCart

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Helper/Api2/Quote.php, src/shell/shopgate_cloudapi_config.php, tests/postman/scripts/forwarder.php
Removing additional calculation for shipping tax amount in order to get rid of issues with edge cases in configurations.
=> MAGENTO-2330: simplified tax export for shipping costs

CHANGELOG.md, docs/swagger.yaml, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Categories.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders/Rest.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders/Rest/Admin/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders/Rest/Customer/V2.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Products.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Resource.php, src/app/code/community/Shopgate/Cloudapi/Model/Order/Source.php, src/app/code/community/Shopgate/Cloudapi/Model/Server.php, src/app/code/community/Shopgate/Cloudapi/controllers/V2Controller.php, src/app/code/community/Shopgate/Cloudapi/etc/api2.xml, src/app/code/community/Shopgate/Cloudapi/etc/config.xml, src/app/code/community/Shopgate/Cloudapi/sql/shopgate_cloudapi_setup/mysql4-upgrade-3.0.0-3.1.0.php, src/app/code/community/Shopgate/Cloudapi/sql/shopgate_cloudapi_setup/mysql4-upgrade-3.1.3-3.2.0.php, src/app/code/community/Shopgate/Cloudapi/sql/shopgate_cloudapi_setup/mysql4-upgrade-3.4.0-3.5.0.php, src/shell/shopgate_cloudapi_db.php, src/var/connect/shopgate_cloudapi.xml, tests/postman/newman/collection.json, tests/postman/newman/globals.json
Magento endpoint to get web checkout orders for PWA 5
=> MAGENTO-2406

.travis.yml, README.md, docs/swagger.yaml, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders.php, src/app/code/community/Shopgate/Cloudapi/Model/Api2/Orders/Rest.php, tests/postman/newman/collection.json, tests/swagger/validator.sh
- Fixed usage of page + shopgate join filters
- Added a badge to readme for swagger validation
- Added travis swagger validation
=> Magento 2414 fix order endpoint v4.1

tests/postman/newman/collection.json
=> add lost facebook login tests

src/app/code/community/Shopgate/Cloudapi/Helper/Request.php
technical improvement. Does not fix any known issue
=> Pi 9480 recognize shopgate request per user agent

CHANGELOG.md, src/app/code/community/Shopgate/Cloudapi/Helper/Request.php
=> Magento 2430 fix app only discounts
